### ISSUE TITLE
compile gif occur error as below

### ISSUE THREAD

**Issue by brilliantsong** [lvgl/lv_lib_gif#1]
gifdec.c:500: error: too few arguments to function 'lv_fs_open'
         gif->fd = lv_fs_open(path, LV_FS_MODE_RD);
   

gifdec.c:524: error: too many arguments to function 'lv_fs_seek'
         lv_fs_seek(gif->fd, pos, k);
  
/**
 * Open a file
 * @param file_p pointer to a lv_fs_file_t variable
 * @param path path to the file beginning with the driver letter (e.g. S:/folder/file.txt)
 * @param mode read: FS_MODE_RD, write: FS_MODE_WR, both: FS_MODE_RD | FS_MODE_WR
 * @return LV_FS_RES_OK or any error from lv_fs_res_t enum
 */
lv_fs_res_t lv_fs_open(lv_fs_file_t * file_p, const char * path, lv_fs_mode_t mode);       
/**
 * Set the position of the 'cursor' (read write pointer) in a file
 * @param file_p pointer to a lv_fs_file_t variable
 * @param pos the new position expressed in bytes index (0: start of file)
 * @return LV_FS_RES_OK or any error from lv_fs_res_t enum
 */
lv_fs_res_t lv_fs_seek(lv_fs_file_t * file_p, uint32_t pos);

**Comment by kisvegabor** [comment]
As the README says you need to use the `feat/new-fs-api` branch of lvgl.
