### ISSUE TITLE
Cant seem to get it to compile

### ISSUE THREAD

**Issue by elgerg** [lvgl/lv_lib_gif#12]
I have taken the latest feature version of the lv_fs and enabled it:
```c
/*File system interface*/
#define LV_USE_FS_IF	1
#if LV_USE_FS_IF
#  define LV_FS_IF_FATFS    '\0'
#  define LV_FS_IF_PC       'S'
#  define LV_FS_IF_POSIX    '\0'
typedef void * lv_fs_drv_user_data_t;
#endif  /*LV_USE_FS_IF*/
```
However when trying to compile it i get:
```
../lv_lib_gif/gifdec.c:504:19: error: too few arguments to function ‘lv_fs_open’
         gif->fd = lv_fs_open(path, LV_FS_MODE_RD);
```
If i set the original file system option to 0 in the conf:
```c
#define LV_USE_FILESYSTEM       0 
```
I got a whole load more errors. 

What am i doing wrong?

**Comment by kisvegabor** [comment]
Do you use the `new-api` branch?

**Comment by elgerg** [comment]
I believe so. I downloaded this:

![image](https://user-images.githubusercontent.com/24628571/103544840-9a8f2500-4e98-11eb-85ca-640b8909aebb.png)

Or is that wrong?

Thanks
Alex

**Comment by kisvegabor** [comment]
Take a look at the README of https://github.com/lvgl/lv_lib_gif

> Compatible with LVGL's feat/new-fs-api branch. If you use the lv_fs_if repository its new-api branch should be used.

**Comment by elgerg** [comment]
Ok. I think i had added that separately where I shouldnt have?

Now it compiles but show an image with No Data in it. The console logs:

Warn: Image draw: src is NULL 	(lv_draw_img.c #77 lv_draw_img())
Warn: lv_img_design: image source type is unknown 	(lv_img.c #728 lv_img_design())

Am I missing something with regards to drivers or initializing them?

I have the following in the config:

/*File system interface*/
#define LV_USE_FS_IF	1
#if LV_USE_FS_IF
#  define LV_FS_IF_FATFS    '\0'
#  define LV_FS_IF_PC       '\0'
#  define LV_FS_IF_POSIX    'L'
#endif  /*LV_USE_FS_IF*/

Ive tried setting IF_PC and IF_POSIX to L with the following in my code:

````c

    /*Temp show image*/
    lv_obj_t * img1 = lv_gif_create_from_file(parent, "L/home/alex/Workspace/LV_HACP/App/Gifs/images.gif");

    lv_obj_align(img1, NULL, LV_ALIGN_CENTER, 600, -20);

````

**Comment by elgerg** [comment]
Oh, ive just noticed something. Let me change that and try again.

**Comment by elgerg** [comment]
No, I thought my path was wrong but it's not.

Any ideas?

**Comment by elgerg** [comment]
It looks like this might be the problem 

````c
static bool f_gif_open(gd_GIF * gif, const void * path, bool is_file)
{
    gif->f_rw_p = 0;
    gif->data = NULL;
#if LV_USE_FILESYSTEM
    gif->fd = NULL;
#endif

    if(is_file) {
#if LV_USE_FILESYSTEM
        gif->fd = lv_fs_open(path, LV_FS_MODE_RD);
        if(gif->fd == NULL) return false;
        else return true;
#else
        return false;
#endif
    } else
    {
        gif->data = path;
        return true;
    }
}
````

If you turn off the LV_USE_FILESYSTEM null is returned. If you enable it then you get compilation errors with too few args.

Any ideas? Do I have the wrong gifdec.c?

Thanks

**Comment by elgerg** [comment]
Finally figured out what you mean by:

Compatible with LVGL's feat/new-fs-api branch. If you use the lv_fs_if repository its new-api branch should be used.

Its a branch of LVGL not a branch of fs_api.

**Comment by elgerg** [comment]
So. I have downloaded the new LVGL branch and that compiles. It still wont load the image.

Am i missing something with regards to drivers for linux? I have tried both PC and posix setting the letter to 'L' and used the following:

lv_obj_t * img1 = lv_gif_create_from_file(parent, "L:/home/alex/Workspace/pc_simulator_sdl_eclipse/App/Gifs/images.gif");

But no data.

It seems to fail somewhere around here:

````c
lv_fs_drv_t * lv_fs_get_drv(char letter)
{
    lv_fs_drv_t * drv;

    _LV_LL_READ(LV_GC_ROOT(_lv_drv_ll), drv) {
        if(drv->letter == letter) {
            return drv;
        }
    }

    return NULL;
}
````

Thanks for the help

**Comment by kisvegabor** [comment]
Are you sure that the file system is working?  E.g. can you open a file with `lv_fs_open`?

**Comment by kisvegabor** [comment]
Both the PC and POSIX versions should work on Linux. 
But first, be sure that you can open and read files without LVGL.

**Comment by elgerg** [comment]
Something like:

```
        strcat(path,rom);
        strcat(path,"/w1_slave");

        // Open the file in the path.
        if((fd = open(path,O_RDONLY)) < 0)
        {
            printf("open error\n");
            return -85.00;
        }
        // Read the file
        if(read(fd,buf,sizeof(buf)) < 0)
        {
            printf("read error\n");
            return -85.00;
        }
        // Returns the first index of 't'.
        _temp = strchr(buf,'t');
        // Read the string following "t=".
        sscanf(_temp,"t=%s",_temp);
        // atof: changes string to float.
        value = atof(_temp)/1000;
        printf("Temp Retrieved: %.2f... ", (double)value);
        close(fd);
```

The above works and reads a temp from a one wire ds18b20 temp sensor.

**Comment by kisvegabor** [comment]
> The above works and reads a temp from a one wire ds18b20 temp sensor.

Wasn't we talking about gifs? How did the DS18B20 come into the picture?

Please try to read gif file. The first 3 characters should be `"GIF"`.

**Comment by elgerg** [comment]
Sorry, i thought you were asking if i could read the file system.

Yes gif reading works:

![image](https://user-images.githubusercontent.com/24628571/104361332-36103d80-550a-11eb-982d-a00b367ef7c0.png)

**Comment by kisvegabor** [comment]
Great!

In `lv_fs_open` you should use `L/App/Gifs/images.gif` because LVGL assumes relative path from the working directory.

**Comment by elgerg** [comment]
Ok. I must be missing something in the initialization of the file system.

![image](https://user-images.githubusercontent.com/24628571/104463914-40821400-55aa-11eb-9301-fa104af10e9d.png)

![image](https://user-images.githubusercontent.com/24628571/104463982-542d7a80-55aa-11eb-9c0e-80e514ea7180.png)

![image](https://user-images.githubusercontent.com/24628571/104464035-63142d00-55aa-11eb-8548-b709ff50a3ae.png)

![image](https://user-images.githubusercontent.com/24628571/104464065-6f988580-55aa-11eb-9385-fb0b1e6bc932.png)

![image](https://user-images.githubusercontent.com/24628571/104464149-87700980-55aa-11eb-889d-e37b9d93dd29.png)

I have the following include:

```
#include "lv_lib_gif/lv_gif.h"
```

Is there anything i have not set or set incorrectly?

**Comment by kisvegabor** [comment]
Have you called `  lv_fs_if_init();`?

**Comment by elgerg** [comment]
I did try but it says its undefined.

![image](https://user-images.githubusercontent.com/24628571/104469579-91950680-55b0-11eb-9d0d-bc5ece0a9425.png)

![image](https://user-images.githubusercontent.com/24628571/104469598-96f25100-55b0-11eb-9794-e7646ce08c49.png)


Am I missing an include?

**Comment by kisvegabor** [comment]
Do you see `lv_fs_if_init()` [here](https://github.com/lvgl/lv_fs_if/blob/new-api/lv_fs_if.c#L52) in your code?
If you add an `#error "built"` to `lv_fs_if.c` do you see the error on build?

**Comment by elgerg** [comment]
No i didnt copy the new fs source into lvgl. I didnt realise that was a requirement.

I get the image displayed now but have a separate issue with the alignment and casting.

I'll do some digging and raise another ticket if there are other problems.

Thanks for the great library and all of the help.
Alex

**Comment by kisvegabor** [comment]
Glad to hear that it finally works :slightly_smiling_face:
