### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by jinxiangwzh** [lvgl/lv_lib_gif#14]
it's very strange, i use my gif picture to convert to c array as the readme file said, but it can't be display the gif, it will fail into a infinite loop in the file of gifdec.c between in line 377 ~390.i use the example gif it will work ok.

**Comment by kisvegabor** [comment]
Let's try to upload and download the gif to https://ezgif.com/
Maybe there is something in your gif that is not supported by the decoder.
