### ISSUE TITLE
 fatal error: sys/types.h: No such file or directory

### ISSUE THREAD

**Issue by oswaldo155** [lvgl/lv_lib_gif#16]
hello, I'm working in mcuxpresso IDE, in my project I already added the files to implement gif images, but I don't have the following files:
#include <sys / types.h>
#include <sys / stat.h>
#include <fcntl.h>
#include <unistd.h>
where can i get them?

**Comment by kisvegabor** [comment]
They came from the 3rd parts gif decoder. I've just removed them because they weren't really required.

**Comment by Dhara910** [comment]
Where is updated gif decoder available, which haven't dependent on sys/types.h files?

**Comment by kisvegabor** [comment]
The library was updated and this include appeared again. I've just removed it.
