### ISSUE TITLE
Hard fault 

### ISSUE THREAD

**Issue by stetzanton** [lvgl/lv_lib_gif#2]
Hey. Trying to run the gif library on stm32f407. I get hardfault after launch. I get "invalid signature" in the console. But the process continues to run after that.
![c9f85ae734](https://user-images.githubusercontent.com/3928606/90937993-aeb61680-e410-11ea-8174-782d8b354c71.jpg)

**Comment by kisvegabor** [comment]
It seems there is no proper error handling in the lib.

"Invalid signature" means the GIf file was invalid.

**Comment by kisvegabor** [comment]
I've added error handling here: 
https://github.com/lvgl/lv_lib_gif/commit/d64a40001fe01e35e01533b8deee942756943617

**Comment by stetzanton** [comment]
can you send any correct gif file for test?

**Comment by kisvegabor** [comment]
it works for me:
![test](https://user-images.githubusercontent.com/7599318/91053982-eb0d9080-e623-11ea-9fef-534a49aff4f5.gif)

**Comment by stetzanton** [comment]
Hardfault is passed. But "invalid signature" is in place. I use your gif file placed in the root of SD-card. 
I also have a problem reading images from the card. All UI elements are created successfully. But the images are not loading. Maybe this is a common problem?
![projects - SmartProjector_407V_LVGLv7CoreSrcmain c - STM32CubeIDE](https://user-images.githubusercontent.com/3928606/91103152-7b26f680-e673-11ea-883d-d071caf64492.jpg)

**Comment by kisvegabor** [comment]
How do you set the path of the files? Do you use LVGL's files system API?
E.g. `S/path/to/image.gif`

**Comment by stetzanton** [comment]
"S:/path/to/image.gif"
But images with errors in .bin format
Problem with cache start after include lv_lib_gif and replace lvgl version (feat/new-fs-api) and lv_fs_if(new-api)

**Comment by kisvegabor** [comment]
You don't need to convert it into bin, just use the gif as it is.

**Comment by stetzanton** [comment]
I do not convert .GIF to .bin. The cache issue was with old files that were loaded from SD card(background pictures). Images from flash(button icons) are loaded and displayed normally.

**Comment by kisvegabor** [comment]
I suggest using a simulator (I use Eclipse you can use other) to have a common platform to investigate the issue.

If you place the images to the projet's root folder and you enable ` LV_FS_IF_PC       'P'` it should work for "normal images":
```
lv_img_set_src(img, "P/my_image.bin");
```

Is it working?

**Comment by stetzanton** [comment]
.bin working good with master-branch jf lvgl
can i use lv_lib_gif with master branch or only with new-fs-api?

**Comment by stetzanton** [comment]
When i use without lv_fs_if library have this errors http://joxi.ru/n2Ybe6hbDObbA6 (with master branch of lvgl .bin files are open good with "S:/path/to/image.bin"). Where i can add disk letter for new-fs-api branch of lvgl?

**Comment by kisvegabor** [comment]
> can i use lv_lib_gif with master branch or only with new-fs-api?

No, I made some changes in the FS API when added the GIF library. 

> When i use without lv_fs_if library have this errors http://joxi.ru/n2Ybe6hbDObbA6 (with master branch of lvgl .bin files are open good with "S:/path/to/image.bin"). Where i can add disk letter for new-fs-api branch of lvgl?

If you don't use `lv_fs_if` you need to register a driver yourself. See here https://docs.lvgl.io/latest/en/html/overview/file-system.html
