### ISSUE TITLE
GIF cannot loop indefinitely

### ISSUE THREAD

**Issue by mlpzaq9998** [lvgl/lv_lib_gif#23]
![3](https://user-images.githubusercontent.com/6046642/114824853-066a1d80-9df8-11eb-950e-0a9de0188905.gif)

ui->Page_clock_img1 = lv_gif_create_from_file(ui->Page_clock, "S:/Astronaut.gif");

**Comment by kisvegabor** [comment]
The gif library sends an `LV_EVENT_LEAVE` when the gif is finished. There you can call `lv_gif_restart(gif_obj)`

**Comment by mlpzaq9998** [comment]
> The gif library sends an `LV_EVENT_LEAVE` when the gif is finished. There you can call `lv_gif_restart(gif_obj)`

Can the process be simplified? Parameterize or follow GIF settings

**Comment by kisvegabor** [comment]
I've pushed some updates. Now it considers the loop count.

There some other changes too so some regression is possible. 
The previous version of gif decoder was buggy in some cases. Now the correct implementation is used but issues more memory.
