### ISSUE TITLE
this lib have compatible with lvgl V6?

### ISSUE THREAD

**Issue by zq190kg** [lvgl/lv_lib_gif#3]
hello,i used lvgl v6,this lib have compatible with lvgl V6?tks

**Comment by kisvegabor** [comment]
You need to use `feat/new-fs-api` of LVGL to work with the GIF library and this branch is based on the latest version (v7.4.0)

So it's not compatible with v6. :slightly_frowning_face:

**Comment by zq190kg** [comment]
THS
