### ISSUE TITLE
About how to convert gif to C array

### ISSUE THREAD

**Issue by moion** [lvgl/lv_lib_gif#31]
I'm a beginner in lvgl.
I want to use lv_lib_gif in my project.And ran the example successfully.
But the [LVGL's online converter](https://lvgl.io/tools/imageconverter) can't convert GIF format.Only support BMP, JPG or PNG.
Is there any way to convert(🥺)

**Comment by kisvegabor** [comment]
Hi, 
if you are using the latest LVGL (not v7) then you can use the gif library right from LVGL. See https://docs.lvgl.io/master/libs/gif.html

Regarding the converter, we are updating to new converter available here https://lvgl.io/tools/imageconverter_new
Please try with it.

**Comment by moion** [comment]
thanks

**Comment by kisvegabor** [comment]
Great, thanks for the feedback.

@embeddedt I've published the new image converter at https://lvgl.io/tools/imageconverter

As it's your merit, could you write a few words about it in a forum announcement?

**Comment by embeddedt** [comment]
Done.
