### ISSUE TITLE
replace SEEK_CUR with LV_FS_SEEK_CUR?

### ISSUE THREAD

**Issue by LikWoody** [lvgl/lv_lib_gif#33]
https://github.com/lvgl/lv_lib_gif/blob/d00fe265666445ee5848380811b1f7b372ed7287/gifdec.c#L181

SEEK_CUR is not support in keil IDE,can we replace off_t with LV_FS_SEEK_CUR? this will easy to port.

**Comment by kisvegabor** [comment]
Please send Pr for the lvgl repository as this lib was merged there.
