### ISSUE TITLE
 GIF parses out redundant images

### ISSUE THREAD

**Issue by jianjunxia** [lvgl/lv_lib_gif#38]
in release/v7, use this GIF，Caused extra images to be parsed, please help to see what caused the problem?
In addition, is there a useful tool for parsing GIF data?
![zoomies_test](https://user-images.githubusercontent.com/35299508/153843819-2c42c9b8-094b-415d-8aa4-59e9f6e2a0a0.gif)

**Comment by jianjunxia** [comment]
![image](https://user-images.githubusercontent.com/35299508/153845103-5fc6b340-8175-4634-b97b-121a4d65c305.png)

**Comment by kisvegabor** [comment]
Is it the same with v8 where gif is already part of lvgl?

**Comment by jianjunxia** [comment]
> Is it the same with v8 where gif is already part of lvgl?

yes, my lvgl version is v7,  latest v7 version of my lv_lib_gif

**Comment by kisvegabor** [comment]
I mean can ou try out in a  simulator with v8 too?

**Comment by jianjunxia** [comment]
> I mean can ou try out in a simulator with v8 too?

yes, you can try it!

**Comment by jianjunxia** [comment]
> I mean can ou try out in a simulator with v8 too?

how about?

**Comment by jianjunxia** [comment]
> I mean can ou try out in a simulator with v8 too?
hi，do you try it? how about it?

**Comment by kisvegabor** [comment]
I meant you can try it out if the issue still persists.  Anyway I've just checked it an v8 it looked fine. 

Can you try it out on your end too with v8?

**Comment by jianjunxia** [comment]
> I meant you can try it out if the issue still persists. Anyway I've just checked it an v8 it looked fine.
> 
> Can you try it out on your end too with v8?

i found this gif background=0xff, when i add this code in gif_open function in release/v7, this gif is shows normal
`   if (gif->bgindex == 0xff)
        gif->bgindex = 0;`

**Comment by jianjunxia** [comment]
so， i think when gif->bgindex = 0xff, it may cause the gif to display abnormally,  do you think so? I need some advice from you

**Comment by jianjunxia** [comment]
Also, I'm developing with lgvl v7 now

**Comment by kisvegabor** [comment]
I think it's just working accidentally. 
I tried a lot optimization things and if I recall correctly the final solution is only included in v8. 

I suggest backporting the [gif decoder from v8](https://github.com/lvgl/lvgl/blob/master/src/extra/libs/gif/gifdec.c) to v7.

**Comment by jianjunxia** [comment]
> 
I have compared the difference between v8 and release/v7 versions of gif parsers and they are no different in my opinion

**Comment by jianjunxia** [comment]
> I think it's just working accidentally. I tried a lot optimization things and if I recall correctly the final solution is only included in v8.
> 
> I suggest backporting the [gif decoder from v8](https://github.com/lvgl/lvgl/blob/master/src/extra/libs/gif/gifdec.c) to v7.

but,i can try it

**Comment by jianjunxia** [comment]
> I think it's just working accidentally. I tried a lot optimization things and if I recall correctly the final solution is only included in v8.
> 
> I suggest backporting the [gif decoder from v8](https://github.com/lvgl/lvgl/blob/master/src/extra/libs/gif/gifdec.c) to v7.

In addition, why does it cause this problem when gif->bgindex = 0xff?

**Comment by kisvegabor** [comment]
It seems the problem is related to the transparent background. [Wikipedia](https://en.wikipedia.org/wiki/GIF) says:
> Each frame can designate one index as a "transparent background color": any pixel assigned this index takes on the color of the pixel in the same position from the background, which may have been determined by a previous frame of animation.

I remember that tested this but there might be some issues.

I suspect that the offending line is this: https://github.com/lvgl/lvgl/blob/master/src/extra/libs/gif/gifdec.c#L486

**Comment by jianjunxia** [comment]
> 



> It seems the problem is related to the transparent background. [Wikipedia](https://en.wikipedia.org/wiki/GIF) says:
> 
> > Each frame can designate one index as a "transparent background color": any pixel assigned this index takes on the color of the pixel in the same position from the background, which may have been determined by a previous frame of animation.
> 
> I remember that tested this but there might be some issues.
> 
> I suspect that the offending line is this: https://github.com/lvgl/lvgl/blob/master/src/extra/libs/gif/gifdec.c#L486
My current solution is： `if (gif->bgindex == 0xff) gif->bgindex = 0`，Do you think this solution is reasonable？I need your help, thanks

**Comment by kisvegabor** [comment]
> My current solution is： if (gif->bgindex == 0xff) gif->bgindex = 0`，Do you think this solution is reasonable？I need your help, thanks

`gif->gce.tindex` is the index of the transparent color. So if it's incorrect then it should be tracked why is not set correctly. 

 By definition, `gif->bgindex = 0` doesn't have any special meaning.

**Comment by jianjunxia** [comment]
> By definition, `gif->bgindex = 0` doesn't have any special meaning

yes,i know `gif->gce.tindex`  is the index of the transparent color, it is included in every frame of the picture, but i use cmd `gifsicle -I  this.gif`， i found every frame index of the transparent is 255=0xff, it doesn't look like any difference

**Comment by jianjunxia** [comment]
i'm tested in v7 lvgl and in v7 lv_lib_gif  do you help me to test it？please

**Comment by jianjunxia** [comment]
![image](https://user-images.githubusercontent.com/35299508/154298938-641e75f3-a16b-4956-bc10-439b23b0e055.png)

**Comment by jianjunxia** [comment]
hi，I know what is causing the above problem，The above gif image is very special, and it has several characteristics that cause the above problems。
When I use `gifsicle --cinfo this.gif,` I find transparent 255 is #000000 of the global colormap and local colormap of this image, and this.gif  `gif->gce.disposal` is always 3，It will cause the following problems：
Step1：in `gif_open function` ， it won't go into the following case：https://github.com/lvgl/lv_lib_gif/blob/27a74507ee73ae462daf8f4d4c2f65b366fc9cfd/gifdec.c#L138-L155

Step2：because `gif->gce.disposal = 3`，it's restore to previous, don't update canvas

Step3：because every frame Local Color Table `gif->gce.tindex= 255,` and this data is #000000

So I think the above situation leads to why the background color has an extra white line.

Also, I think white background color is not supported in release/v7，I think the code should be changed like this：
delete this line code： `if (bgcolor[0] || bgcolor[1] || bgcolor [2])`

**Comment by jianjunxia** [comment]
in this issues，https://github.com/lvgl/lv_lib_gif/issues/15 his problem is similar to mine,  But I don't think your explanation is accurate：https://github.com/lvgl/lv_lib_gif/issues/15#issuecomment-768136218
 in his gif https://github.com/lvgl/lv_lib_gif/issues/15#issuecomment-765151040 and https://github.com/lvgl/lv_lib_gif/issues/15#issuecomment-765171277
 
 I found a similar question，use cmd： `gifsicle --cinfo xx.gif`，this global color table[63] = #000000， and this background = 63，so when parsing these two gifs, the code of step1 above cannot be entered.
But luckily，this two gif `gif->gce.disposal = 2`，so, it can  restore to background color，so，this why a white line flashes on the background.
I think there are two problems in release/v7 lv_lib_gif,
1：when background data = #000000, it's caused some problem.
2：in v7 lvgl it's not set white background

**Comment by kisvegabor** [comment]
I think I mostly understand :slightly_smiling_face: 
But isn't `#000000` black?

**Comment by jianjunxia** [comment]
> I think I mostly understand 🙂 But isn't `#000000` black?

but，

> I think I mostly understand 🙂 But isn't `#000000` black?

In actual operation, it does cause the problem

**Comment by jianjunxia** [comment]
> I think I mostly understand 🙂 But isn't `#000000` black?

when i delete `if (bgcolor[0] || bgcolor[1] || bgcolor [2])` 
All gifs are back to normal

and i think this `if (bgcolor[0] || bgcolor[1] || bgcolor [2])`  looks useless

**Comment by jianjunxia** [comment]
> I think I mostly understand 🙂 But isn't `#000000` black?

yes, in RGB #0000000 is black，but, the actual running scenario does
and when i delete this code `if (bgcolor[0] || bgcolor[1] || bgcolor [2])`  every gif run is back to normal

this code `if (bgcolor[0] || bgcolor[1] || bgcolor [2])` llooks useless

**Comment by kisvegabor** [comment]
To be honest I also don't know what is the point of `if (bgcolor[0] || bgcolor[1] || bgcolor [2])`.

So can you confirm that removing it all works well?

**Comment by jianjunxia** [comment]
yes，i can



---Original---
From: "Gabor ***@***.***&gt;
Date: Thu, Feb 17, 2022 21:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lvgl/lv_lib_gif]  GIF parses out redundant images (Issue #38)




 
To be honest I also don't know what is the point of if (bgcolor[0] || bgcolor[1] || bgcolor [2]).
 
So can you confirm that removing it all works well?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jianjunxia** [comment]
yes, I can



---Original---
From: "Gabor ***@***.***&gt;
Date: Thu, Feb 17, 2022 21:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lvgl/lv_lib_gif]  GIF parses out redundant images (Issue #38)




 
To be honest I also don't know what is the point of if (bgcolor[0] || bgcolor[1] || bgcolor [2]).
 
So can you confirm that removing it all works well?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kisvegabor** [comment]
Great! 

I fixed it in lvgl/master here https://github.com/lvgl/lvgl/commit/b1e2c0665829aa489f444169ce80fcd7cdf487bb

**Comment by jianjunxia** [comment]
> Great!
> 
> I fixed it in lvgl/master here [lvgl/lvgl@b1e2c06](https://github.com/lvgl/lvgl/commit/b1e2c0665829aa489f444169ce80fcd7cdf487bb)

Thanks，i will colse this issue

**Comment by kisvegabor** [comment]
Thanks for the debugging and finding the root of this issue! :1st_place_medal:
