### ISSUE TITLE
example.gif does not convert to example.c as described using Online Image Converter

### ISSUE THREAD

**Issue by crhayden** [lvgl/lv_lib_gif#41]
If I convert the example.gif to a c array using the Online Image Converter as described (color format = RAW; output format = C array) I get a different result than the example_gif.c. See attached
[example.txt](https://github.com/lvgl/lv_lib_gif/files/8258858/example.txt)

**Comment by kisvegabor** [comment]
Does it still work well?

Maybe the gif has changed in the meantime and C file wasn't updated.
