### ISSUE TITLE
CANT FIND DEFINE

### ISSUE THREAD

**Issue by chliii** [lvgl/lv_lib_gif#5]
![error](https://user-images.githubusercontent.com/34575082/93196145-9ff72100-f77c-11ea-8bd4-3bb2940cfaa8.JPG)

**Comment by chliii** [comment]
![error2](https://user-images.githubusercontent.com/34575082/93197103-d2ede480-f77d-11ea-88d7-354d2b0ab200.JPG)
run on the CLION for ESP32

**Comment by kisvegabor** [comment]
As stated in the README you need to use the `feat/new-fs-api` branch of LVGL with the GIF decoder.

**Comment by chliii** [comment]
Thanks your answer.

But,when I run the program, the screen show "No data".

    lv_obj_t * img = lv_gif_create_from_file(lv_scr_act(),"F:/ESP32/esp-gif/src/ship.gif");

Maybe I set a wrong path?

**Comment by chliii** [comment]
![error](https://user-images.githubusercontent.com/34575082/93448871-aa452680-f906-11ea-8c18-4a71f7e9d361.JPG)
![2](https://user-images.githubusercontent.com/34575082/93448887-ae714400-f906-11ea-84df-6fa082a7e228.JPG)

And,did I set the path is true ?
lv_obj_t *img = lv_gif_create_from_file(lv_scr_act(), "p/ship.gif");
    lv_obj_align(img, NULL, LV_ALIGN_CENTER, 0, 0);

**Comment by chliii** [comment]
the function "ftruncate" cant compile on the ESP32.

#if defined(__CYGWIN__) || defined(__rtems__) || defined(__aarch64__) || defined (__arm__) || defined(__sh__) || defined(__SPU__)
#if !defined(__INSIDE_CYGWIN__)
int     _EXFUN(ftruncate, (int __fd, off_t __length));
int     _EXFUN(truncate, (const char *, off_t __length));
#endif
#endif

**Comment by kisvegabor** [comment]
Hm, if `ftruncate` is a standard C function however it's important to support ESP32. If you remove this function the rest is working?

**Comment by chliii** [comment]
Hi,
if I remove this function the rest is working,but,the screen only show _No data_.

**Comment by chliii** [comment]
My WARNING and the screen
![4](https://user-images.githubusercontent.com/34575082/94106193-7f5e5380-fe6d-11ea-9e1c-be435048abf7.png)
![3](https://user-images.githubusercontent.com/34575082/94106200-81c0ad80-fe6d-11ea-863a-92e6e5954756.jpg)

**Comment by kisvegabor** [comment]
How do you set the path of the gif?

Please enable the [logging of LVGL](https://docs.lvgl.io/latest/en/html/porting/log.html) to see what's going on.
