### ISSUE TITLE
How to convert the gif data?

### ISSUE THREAD

**Issue by KiraVerSace** [lvgl/lv_lib_gif#6]
Hi
Thank you for your repo, and there is a gif and I don't  how to convert it to
`lv_obj_t * img = lv_gif_create_from_data(parent, gif_data);`
gif_data?

Is there any tools?
I want to slice my gif to 10 frames/second then show the img in the power on at first, but now I want to use your method.

**Comment by kisvegabor** [comment]
Hi,

I've updated the README the describe it. 
See https://github.com/lvgl/lv_lib_gif/commit/230b6d60f854d118ce6af230424afed7d5353599

**Comment by KiraVerSace** [comment]
Thank you!!!!
I convert my video to gif then display it!
