### ISSUE TITLE
If I just want to use the c_array to display the GIF

### ISSUE THREAD

**Issue by KiraVerSace** [lvgl/lv_lib_gif#7]
If I just want to use the c_array to display the GIF, would you like to simplify the  code, and remove the lv_fs_if, it's difficult for me to do it.

because I add the lv_fs_if and lv_lib_gif library and enable 
```
/* 1: Enable file system (might be required for images */
#define LV_USE_FILESYSTEM       1	// FIXME:0->1
```

and add

```
/*File system interface*/
#define LV_USE_FS_IF	1
#if LV_USE_FS_IF
#  define LV_FS_IF_FATFS    '\0'
#  define LV_FS_IF_PC       '\0'
#endif  /*LV_USE_FS_IF*/
```

there also many errors in the compile. Sorry, Could you help me, and I am from China, and do not good at English.

Thank you for your contribution!

<img width="880" alt="iShot2020-10-17 03 35 03" src="https://user-images.githubusercontent.com/55439370/96301434-c6cd9f00-1029-11eb-9619-600e1e35d5fc.png">

**Comment by kisvegabor** [comment]
I can update the gif library to work well `LV_USE_FILESYSTEM 0` (without `lv_fs_if`).

Would it work for you?

**Comment by KiraVerSace** [comment]
> I can update the gif library to work well `LV_USE_FILESYSTEM 0` (without `lv_fs_if`).
> 
> Would it work for you?

no if you dont use the lv_fs_if it will be more errors, I include the two folders.

Now in my project I use 20 frams/second to display the animations, haha!

**Comment by kisvegabor** [comment]
I meant to make the gif library work with `LV_USE_FILESYSTEM 0` without `lv_fs_if` or any other FS related stuff.

**Comment by KiraVerSace** [comment]
yes I have try it set LV_USE_FILESYSTEM 0, but errors happens too

**Comment by kisvegabor** [comment]
I've pushed a fix, please try with the latest version,

**Comment by KiraVerSace** [comment]
> I've pushed a fix, please try with the latest version,

thank you for your contribution, but I doubt if I use the gif library or use too many images like 20fps, which will be better and which use less flash size?

**Comment by kisvegabor** [comment]
gif is compressed fo needs less flash but slower becasuse needs decompression.
gif has a 8 bit palette so it can have only 256 colors per frame.

Finally are you happy with 20FPS or is it too slow for you?

**Comment by chliii** [comment]
朋友 可以加个联系方式吗

**Comment by chliii** [comment]
@KiraVerSace 朋友 可以加个联系方式吗
