### ISSUE TITLE
hi,how to disable gif and re-enable gif?

### ISSUE THREAD

**Issue by zq190kg** [lvgl/lv_lib_gif#8]
hi,I need to display GIF images on different pages,Some pages show gif, some don't,How to enable GIF images and restart GIF images when switching pages（different gif source，different coordinate on different page），Thank you for your reply。

**Comment by zq190kg** [comment]
I've done it，
1：del gif lv_obj_t
2:  del  task
3:create gif obj
4 restart task

**Comment by kisvegabor** [comment]
Have you tried to use the `lv_gif_restart` function?

**Comment by zq190kg** [comment]
i tried restart func,it means  gif keeps running,

**Comment by kisvegabor** [comment]
Ah, so do you need functions like `lv_gif_pause()` and `lv_gif_resume()`?
